# Generated by Django 3.2.6 on 2022-09-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20220920_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
