# Generated by Django 3.2.6 on 2022-10-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_orderdetail_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
