# Generated by Django 3.2.6 on 2022-12-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referralrelationship_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrelationship',
            name='refer_token',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
