# Generated by Django 3.2.6 on 2022-12-20 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0003_alter_referralrelationship_refer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrelationship',
            name='invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='invited'),
        ),
    ]
