# Generated by Django 3.2.6 on 2022-09-23 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Package+', to='packages.packages'),
        ),
    ]
