# Generated by Django 3.2.6 on 2021-08-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vps_vps_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='instance_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
