# Generated by Django 3.2.6 on 2021-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vps_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
