# Generated by Django 3.2.6 on 2021-08-14 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_vps_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='vps',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='vps',
            name='date_modified',
            field=models.DateField(blank=True, null=True, verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='vps',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modifier+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='vps',
            name='sub_type',
            field=models.CharField(choices=[('vps', 'VPS'), ('proxy', 'PROXY')], default='vps', max_length=20),
        ),
    ]
