# Generated by Django 3.2.6 on 2021-08-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_templates_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='instance_id',
            new_name='template_id',
        ),
        migrations.RenameField(
            model_name='templates',
            old_name='instance_name',
            new_name='template_name',
        ),
    ]
