# Generated by Django 3.2.6 on 2021-08-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210815_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='obj_type',
            field=models.CharField(choices=[('vps', 'VPS'), ('proxy', 'PROXY')], default='vps', max_length=20),
        ),
    ]
