# Generated by Django 3.2.6 on 2021-08-18 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_templates_obj_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Custom User+', to=settings.AUTH_USER_MODEL),
        ),
    ]
