# Generated by Django 3.2.6 on 2021-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_create_by_vps_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='user_attached',
            field=models.BooleanField(default=False),
        ),
    ]
