# Generated by Django 3.2.6 on 2021-08-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_vps_user_attached'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('access', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='vps',
            name='aws_account_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
