# Generated by Django 3.2.6 on 2021-08-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210819_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vps',
            name='aws_account_id',
        ),
        migrations.AddField(
            model_name='vps',
            name='aws_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.awsaccounts'),
        ),
    ]
