# Generated by Django 3.2.6 on 2021-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210819_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vps',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vps',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
