# Generated by Django 3.2.6 on 2021-08-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_accountlogs_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlogs',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='VPS+', to='main.vps'),
        ),
    ]
