# Generated by Django 3.2.6 on 2021-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_vps_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogs',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
