# Generated by Django 3.2.6 on 2021-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_vps_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogs',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified'),
        ),
    ]
