# Generated by Django 3.2.6 on 2021-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_accountlogs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='rdp_file',
            field=models.FileField(blank=True, default=None, max_length=254, null=True, upload_to='rdp_files/'),
        ),
    ]
