# Generated by Django 3.2.6 on 2021-08-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_vps_rdp_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Start Modified')),
                ('stop_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Stop Modified')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='VPS+', to='main.vps')),
            ],
        ),
        migrations.AddField(
            model_name='vps',
            name='current_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usage+', to='main.usage'),
        ),
    ]
