# Generated by Django 3.2.6 on 2021-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_vps_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='rdp_file',
            field=models.FileField(blank=True, default='settings.RDP_FOLDER/rdp_file.rdp', max_length=254, null=True, upload_to='rdp_files/'),
        ),
    ]
