# Generated by Django 3.2.6 on 2021-08-23 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0031_templates_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='aws_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.awsaccounts'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='super_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Super User+', to=settings.AUTH_USER_MODEL, verbose_name='Super User'),
        ),
    ]
