# Generated by Django 3.2.6 on 2021-08-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210823_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='port',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vps',
            name='ssh_key',
            field=models.FileField(blank=True, default='settings.RDP_FOLDER/rdp_file.rdp', max_length=254, null=True, upload_to='ssh_keys/'),
        ),
    ]
