# Generated by Django 3.2.6 on 2021-08-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210824_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='key_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
