# Generated by Django 3.2.6 on 2021-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_vps_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='key_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ssh_key',
            field=models.FileField(blank=True, default='settings.RDP_FOLDER/rdp_file.rdp', max_length=254, null=True, upload_to='ssh_keys/'),
        ),
    ]
