# Generated by Django 3.2.6 on 2021-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210825_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Modified'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stop Modified'),
        ),
    ]
