# Generated by Django 3.2.6 on 2021-08-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210826_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Start Modified'),
        ),
    ]
