# Generated by Django 3.2.6 on 2021-08-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_usage_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Modified'),
        ),
    ]
