# Generated by Django 3.2.6 on 2021-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_usage_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
