# Generated by Django 3.2.6 on 2021-08-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_usage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='proxy_details',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vps',
            name='proxy_details_set',
            field=models.BooleanField(default=False),
        ),
    ]
