# Generated by Django 3.2.6 on 2021-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20210831_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='proxy_details',
            field=models.CharField(default='', max_length=50),
        ),
    ]
