# Generated by Django 3.2.6 on 2021-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_vps_proxy_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccounts',
            name='pssword',
            field=models.CharField(default='centos', max_length=50),
        ),
        migrations.AddField(
            model_name='awsaccounts',
            name='username',
            field=models.CharField(default='centos', max_length=50),
        ),
    ]
