# Generated by Django 3.2.6 on 2021-09-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210901_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awsaccounts',
            old_name='pssword',
            new_name='password',
        ),
    ]
