# Generated by Django 3.2.6 on 2021-09-08 10:05

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20210905_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpic',
            name='banner_file',
            field=stdimage.models.StdImageField(blank=True, default='payment.jpg', null=True, upload_to='payment/', verbose_name='Payment Banner'),
        ),
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\New folder\\rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
    ]
