# Generated by Django 3.2.6 on 2021-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210908_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\test\\rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
    ]
