# Generated by Django 3.2.6 on 2022-01-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20220120_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='aws_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.awsaccounts'),
        ),
    ]
