# Generated by Django 3.2.6 on 2022-02-13 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0054_alter_vps_aws_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\sasa\\rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
        migrations.RemoveField(
            model_name='templates',
            name='super_user',
        ),
        migrations.AddField(
            model_name='templates',
            name='super_user',
            field=models.ManyToManyField(related_name='_main_templates_super_user_+', to=settings.AUTH_USER_MODEL, verbose_name='Super User'),
        ),
    ]
