# Generated by Django 3.2.6 on 2022-02-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20220213_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('csv_file', models.FileField(blank=True, default='/home/tiger/awsvps/src/rdprdp_file.rdp', max_length=254, null=True, upload_to='csv/')),
            ],
        ),
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='/home/tiger/awsvps/src/rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
    ]
