# Generated by Django 3.2.6 on 2022-05-24 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0057_auto_20220524_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='super_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Super Seller'),
        ),
    ]
