# Generated by Django 3.2.6 on 2022-05-24 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0058_vps_super_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='sellers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Avail To Sellers'),
        ),
    ]
