# Generated by Django 3.2.6 on 2022-05-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0059_templates_sellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='sellers',
        ),
        migrations.CreateModel(
            name='SellerTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date created')),
                ('date_modified', models.DateField(blank=True, null=True, verbose_name='Date Modified')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modifier+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('sellers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Avail To Sellers')),
                ('template', models.ManyToManyField(related_name='_main_sellertemplates_template_+', to=settings.AUTH_USER_MODEL, verbose_name='Super User')),
            ],
        ),
    ]
