# Generated by Django 3.2.6 on 2022-05-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20220524_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellertemplates',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
