# Generated by Django 3.2.6 on 2022-05-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20220524_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='sellertemplates',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date created'),
        ),
    ]
