# Generated by Django 3.2.6 on 2022-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20220528_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellertemplates',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\tom\\rdprdp_file.rdp', max_length=254, null=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\tom\\rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
    ]
