# Generated by Django 3.2.6 on 2022-06-23 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0066_templates_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellertemplates',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller+', to=settings.AUTH_USER_MODEL, verbose_name='Avail To Sellers'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\tom_clone\\rdprdp_file.rdp', max_length=254, null=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\tom_clone\\rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
    ]
