# Generated by Django 3.2.6 on 2022-08-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20220821_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.AlterField(
            model_name='templates',
            name='obj_type',
            field=models.CharField(choices=[('vps', 'VPS'), ('proxy', 'PROXY'), ('vpn', 'VPN')], default='vps', max_length=20),
        ),
        migrations.AlterField(
            model_name='vps',
            name='obj_type',
            field=models.CharField(choices=[('vps', 'VPS'), ('proxy', 'PROXY'), ('vpn', 'VPN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vps',
            name='sub_type',
            field=models.CharField(choices=[('vps', 'VPS'), ('proxy', 'PROXY'), ('vpn', 'VPN')], default='vps', max_length=20),
        ),
    ]
