# Generated by Django 3.2.6 on 2022-09-05 12:21

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20220904_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogs',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='accountlogs',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='sellertemplates',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, verbose_name='Cost Per Item'),
        ),
        migrations.AlterField(
            model_name='sellertemplates',
            name='total_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='templates',
            name='total_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='vps',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14),
        ),
    ]
