# Generated by Django 3.2.6 on 2022-09-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20220905_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
