# Generated by Django 3.2.6 on 2022-09-19 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0073_vps_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='super_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='_main_templates_super_user_+', to=settings.AUTH_USER_MODEL, verbose_name='Super User'),
        ),
    ]
