# Generated by Django 3.2.6 on 2022-09-20 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0074_alter_templates_super_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogs',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account User+', to='main.accounts'),
        ),
        migrations.AlterField(
            model_name='accountlogs',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VPS+', to='main.vps'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Custom User+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellertemplates',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller+', to=settings.AUTH_USER_MODEL, verbose_name='Avail To Sellers'),
        ),
        migrations.AlterField(
            model_name='sellertemplates',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Templates+', to='main.templates', verbose_name='Templates'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='aws_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.awsaccounts'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VPS+', to='main.vps'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='current_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usage+', to='main.usage'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Templates+', to='main.templates'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Custom User+', to=settings.AUTH_USER_MODEL),
        ),
    ]
