# Generated by Django 3.2.6 on 2022-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20220928_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='instance_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='instance_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='port',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='summary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='vps_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
