# Generated by Django 3.2.6 on 2022-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_alter_vps_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date Modified'),
        ),
    ]
