# Generated by Django 3.2.6 on 2022-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20221228_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='date_created',
            field=models.DateField(null=True, verbose_name='Date created'),
        ),
    ]
