# Generated by Django 3.2.6 on 2023-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20230201_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='cloud',
            field=models.CharField(choices=[('aws', 'AWS'), ('globalcloud', 'Global Cloud')], default='aws', max_length=20),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\gold\\rdprdp_file.rdp', max_length=254, null=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='D:\\work\\tom\\gold\\rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
    ]
