# Generated by Django 3.2.6 on 2023-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20230524_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(blank=True, default='/home/tiger/awsvps/src/rdprdp_file.rdp', max_length=254, null=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='/home/tiger/awsvps/src/rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='cloud',
            field=models.CharField(choices=[('aws', 'AWS'), ('goldproxyvps', 'Gold Proxy Vps')], default='aws', max_length=20),
        ),
    ]
