# Generated by Django 3.2.6 on 2023-06-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20230524_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(blank=True, default='/home/nathan-nyawaya/Station-P/Client-Products/python/saroj/src/rdprdp_file.rdp', max_length=254, null=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='/home/nathan-nyawaya/Station-P/Client-Products/python/saroj/src/rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
    ]
