# Generated by Django 3.2.6 on 2023-07-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20230628_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(blank=True, default='/home/globalvpsproxy/globalvpsproxy/rdprdp_file.rdp', max_length=254, null=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='rdpfile',
            name='rdp_file',
            field=models.FileField(blank=True, default='/home/globalvpsproxy/globalvpsproxy/rdprdp_file.rdp', max_length=254, null=True, upload_to='rdp/'),
        ),
    ]
