# Generated by Django 3.2.6 on 2021-08-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='county',
        ),
    ]
