# Generated by Django 3.2.6 on 2021-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_customuser_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
