# Generated by Django 3.2.6 on 2021-09-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_loginmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='username is required', max_length=20, null=True, unique=True),
        ),
    ]
