# Generated by Django 3.2.6 on 2021-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmessage',
            name='basic',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User Accounts Login Message'),
        ),
        migrations.AlterField(
            model_name='loginmessage',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Super User Accounts Login Message'),
        ),
    ]
