# Generated by Django 3.2.6 on 2022-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='User is a seller', verbose_name='Is seller'),
        ),
    ]
