# Generated by Django 3.2.6 on 2022-06-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20220623_1243'),
        ('authenticate', '0010_customuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seller_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.sellertemplates'),
        ),
    ]
