# Generated by Django 3.2.6 on 2022-09-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_auto_20220623_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alias',
            field=models.CharField(help_text='Username is Required', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Username is Required', max_length=20, null=True, unique=True),
        ),
    ]
