# Generated by Django 3.2.6 on 2022-09-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_alter_loggedinuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_normal',
            field=models.BooleanField(default=False, help_text='User is a Normal User', verbose_name='Is Normal'),
        ),
    ]
