# Generated by Django 3.2.6 on 2022-12-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_customuser_is_normal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
