# Generated by Django 3.2.6 on 2022-12-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0022_alter_whatsappnumber_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnumber',
            name='link',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
