# Generated by Django 3.2.6 on 2022-12-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0023_alter_whatsappnumber_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnumber',
            name='link',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Telegram Link'),
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp Phone Number '),
        ),
    ]
