# Generated by Django 3.2.6 on 2022-12-27 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0024_auto_20221224_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='My inviter+', to=settings.AUTH_USER_MODEL, verbose_name='My inviter'),
        ),
    ]
