# Generated by Django 3.2.6 on 2023-02-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0025_customuser_my_inviter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Header')),
                ('subtext', models.CharField(blank=True, max_length=1000, null=True, verbose_name='sub text')),
            ],
        ),
    ]
