# Generated by Django 3.2.6 on 2023-02-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0026_bannermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermessage',
            name='header',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='bannermessage',
            name='subtext',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='sub text'),
        ),
    ]
