# Generated by Django 3.2.6 on 2023-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0027_auto_20230201_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=500)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
