# Generated by Django 3.2.6 on 2023-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0028_dailynews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynews',
            name='content',
            field=models.TextField(default='Welcome to Proxy World', max_length=500),
        ),
    ]
