# Generated by Django 3.2.6 on 2023-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0029_alter_dailynews_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('video_id', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
